#!/bin/bash
#Assignment 3
#Ian Brauning

cd ~/Documents/

#1:
sed '/zoo/Id' pandas.tsv > panda_zoos.txt

#2:
awk -F'\t' '{print $1, $4, $2}' pandas.tsv | sort -k3 > sorted_pandas.txt

#3:
grep -v "location" pandas.tsv | awk '{print $5}' | sort -u > panda_zoos_A2Z.txt

#4:
sed -E 's/\bfemale\b/F/g; s/\bmale\b/M/g' pandas.tsv > panda_m_f.txt

#5:
grep -w "female" pandas.tsv | grep -ic "october"

#6:
grep -n '' pandas.tsv > panda_names.txt

#7:
sed -n '1p;6p;17p' pandas.tsv > lines_1_6_17.txt

#8:
grep -i "x" pandas.tsv > x_lines.txt

#9:
awk 'NR>1 {print $5}' pandas.tsv | sort | uniq -u > unique_places.txt

#10:
awk 'NR>1 {if ($4 <= 10) print $1, $4}' pandas.tsv | sort -k2 -n > young_pandas.txt
