#!/bin/bash
#Assignment 4
#Ian Brauning

cd ~/Documents/

#1
makeblastdb -in database_mystery_transcripts.fasta -dbtype nucl -out database_mystery_transcripts

#2
makeblastdb -in database_mystery_proteins.fasta -dbtype prot -out database_mystery_proteins

#3
blastn -query query_mystery_nucleotide.fasta -db database_mystery_transcripts -evalue 1e-3 -max_target_seqs 5 -outfmt 7 -out nucleotide_results.out

#4
#T010027234997 at 91.965% identity

#5
awk '$3 > 90' nucleotide_results.out > most_similar.txt

#6
blastp -query query_mystery_protein.fasta -db database_mystery_proteins -evalue 1e-5 -max_target_seqs 15 -outfmt 7 -out protein_results.out

#7
#P010027090796, P010027090798, P010027073865, P010027077695

#8
#ANSWER = Coffea arabica

#9
#ANSWER = Gardenia jasminoides

#10
#ANSWER = Catalase
